spring.application.name=TelaLogin

# Carrega variáveis sensíveis do arquivo .env (não versionado)
spring.config.import=optional:file:.env[.properties]

# =========================================================
# USUÁRIO
# =========================================================

app.user.username=leo.euricobete@gmail.com
app.user.password=4321
app.user.name=Leo


# =========================================================
# ADMINISTRADOR
# =========================================================

app.admin.username=admin
app.admin.password=1234
app.admin.name=Administrador


# =========================================================
# MÉDICO
# =========================================================

app.medico.username=medico
app.medico.password=12345
app.medico.name=Médico


# =========================================================
# GMAIL
# =========================================================

# https://myaccount.google.com/apppasswords
# sua senha de app aqui (É necessário ativar a autenticação de dois fatores antes no Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


# =========================================================
# GOOGLE reCAPTCHA
# =========================================================

recaptcha.site-key=${RECAPTCHA_SITE_KEY}
recaptcha.secret-key=${RECAPTCHA_SECRET_KEY}