-- =========================================================
-- BANCO DO MEDVITA: CRIA TODAS AS TABELAS
-- Rode no Supabase: SQL Editor > New query > cole tudo > Run
-- =========================================================

-- Se você já tinha rodado a versão antiga deste script (tabela "users"),
-- tire o "--" da linha abaixo para apagá-la antes. Isso apaga os pacientes
-- que já estavam cadastrados nela.
-- drop table if exists public.users;

-- O admin NÃO fica no banco: ele vem do application.properties.


-- =========================================================
-- PACIENTES (models/Paciente.java)
-- Cadastrados pela página /register. É também o login do paciente.
-- =========================================================

create table if not exists public.pacientes (
    id               bigint      generated by default as identity primary key,
    email            text        not null unique,
    password_hash    text        not null,
    nome             text        not null,
    cpf              text        not null unique,   -- só números
    telefone         text        not null,
    endereco         text        not null,
    data_nascimento  date        not null,
    created_at       timestamptz not null default now()
);


-- =========================================================
-- PROFISSIONAIS DA SAÚDE (models/ProfissionalSaude.java)
-- Cadastrados pelo admin na página /admin/medicos. É também o login do médico.
-- =========================================================

create table if not exists public.profissionais_saude (
    id                     bigint      generated by default as identity primary key,
    nome                   text        not null,
    registro_profissional  text        not null unique,   -- ex.: CRM 123456-MG
    especialidade          text        not null,          -- ex.: Cardiologia
    telefone               text        not null,
    email                  text        not null unique,
    password_hash          text        not null,
    created_at             timestamptz not null default now()
);


-- =========================================================
-- QUARTOS (models/Quarto.java)
-- =========================================================

create table if not exists public.quartos (
    id                 bigint      generated by default as identity primary key,
    numero             text        not null unique,
    andar              integer     not null,
    capacidade_maxima  integer     not null check (capacidade_maxima > 0),
    ocupacao_atual     integer     not null default 0,
    created_at         timestamptz not null default now(),

    -- Regra de Negócio 5: a ocupação nunca passa da capacidade
    check (ocupacao_atual between 0 and capacidade_maxima)
);


-- =========================================================
-- CONSULTAS (models/Consulta.java)
-- =========================================================

create table if not exists public.consultas (
    id               bigint      generated by default as identity primary key,
    paciente_id      bigint      not null references public.pacientes(id),
    profissional_id  bigint      not null references public.profissionais_saude(id),
    data             date        not null,
    horario          time        not null,
    motivo           text        not null,
    observacoes      text,                              -- observações médicas
    status           text        not null default 'AGENDADA'
                     check (status in ('AGENDADA', 'REALIZADA', 'CANCELADA')),
    created_at       timestamptz not null default now()
);

-- Regra de Negócio 3: um profissional não pode ter duas consultas no mesmo
-- dia e horário. Consultas canceladas não contam (liberam o horário).
create unique index if not exists consultas_profissional_horario_uk
    on public.consultas (profissional_id, data, horario)
    where status <> 'CANCELADA';


-- =========================================================
-- INTERNAÇÕES (models/Internacao.java)
-- =========================================================

create table if not exists public.internacoes (
    id                  bigint      generated by default as identity primary key,
    paciente_id         bigint      not null references public.pacientes(id),
    profissional_id     bigint      not null references public.profissionais_saude(id),
    quarto_id           bigint      not null references public.quartos(id),
    data_entrada        date        not null,
    data_prevista_alta  date        check (data_prevista_alta >= data_entrada),
    data_efetiva_alta   date        check (data_efetiva_alta >= data_entrada),  -- vazia enquanto internado
    observacoes         text,
    created_at          timestamptz not null default now()
);

-- Um paciente não pode estar internado duas vezes ao mesmo tempo.
create unique index if not exists internacoes_paciente_internado_uk
    on public.internacoes (paciente_id)
    where data_efetiva_alta is null;


-- =========================================================
-- HISTÓRICO MÉDICO (models/HistoricoMedico.java)
-- Não tem tabela: é montado a partir das consultas e internações.
-- =========================================================


-- =========================================================
-- SEGURANÇA (RLS)
-- =========================================================

-- O Supabase expõe o schema "public" numa API REST pública (usa a "anon key",
-- que fica visível em qualquer front-end). Sem RLS, qualquer pessoa com essa
-- chave conseguiria ler as tabelas, inclusive os hashes de senha.
-- Ligando o RLS SEM criar nenhuma policy, a API REST fica bloqueada.
-- O Spring Boot continua funcionando porque conecta como "postgres", o dono
-- das tabelas, que não é afetado pelo RLS.
alter table public.pacientes           enable row level security;
alter table public.profissionais_saude enable row level security;
alter table public.quartos             enable row level security;
alter table public.consultas           enable row level security;
alter table public.internacoes         enable row level security;
